<a href="https://colab.research.google.com/github/ShahidMazumdarAI-hub/ML_MODELS_Via_FastAPI/blob/main/MLModelsviaFastApi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [ ]:
import sklearn

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
from sklearn.pipeline import Pipeline

In [ ]:
from sklearn.compose import ColumnTransformer

In [ ]:
from sklearn.metrics import classification_report, accuracy_score

In [ ]:
import numpy as np

In [ ]:
list1 = {
    "Age":[64,51,67,60,40],
    "Weight":[59.8,100.6,114.8,117.8,70.0],
    "Height":[1.63,1.68,1.74,1.66,1.59],
    "income_lpa":[3.87000,11.99,0.61000,50.000,28.16664],
    "smoker":["False","True","True","True","True"],
    "city":["Mumbai","BLR","Mumbai","Lucknow","BLR"],
    "Occupation":["Retired","unemployed","Retired","business","Govt_job"],
    "INSURANCE_PREMIUM_category":["Medium","High","High","High","Low"],
}
f = pd.DataFrame(list1)  #Here this DataFrame is like an excelsheet for storing datas,so its a func which will convert this list1 into an excelsheet.....DOWN in the o/p O,1,2,3 are actually INDEXES which refers to Rows and name marks city designat... are columns here

f

,Age,Weight,Height,income_lpa,smoker,city,Occupation,INSURANCE_PREMIUM_category
0,64,59.8,1.63,3.87000,False,Mumbai,Retired,Medium
1,51,100.6,1.68,11.99000,True,BLR,unemployed,High
2,67,114.8,1.74,0.61000,True,Mumbai,Retired,High
3,60,117.8,1.66,50.00000,True,Lucknow,business,High
4,40,70.0,1.59,28.16664,True,BLR,Govt_job,Low

In [ ]:
f.to_csv('insurance.csv')

In [ ]:
f = pd.read_csv('insurance.csv')
f

,Unnamed: 0,Age,Weight,Height,income_lpa,smoker,city,Occupation,INSURANCE_PREMIUM_category
0,0,64,59.8,1.63,3.87000,False,Mumbai,Retired,Medium
1,1,51,100.6,1.68,11.99000,True,BLR,unemployed,High
2,2,67,114.8,1.74,0.61000,True,Mumbai,Retired,High
3,3,60,117.8,1.66,50.00000,True,Lucknow,business,High
4,4,40,70.0,1.59,28.16664,True,BLR,Govt_job,Low

In [ ]:
f

,Unnamed: 0,Age,Weight,Height,income_lpa,smoker,city,Occupation,INSURANCE_PREMIUM_category
0,0,64,59.8,1.63,3.87000,False,Mumbai,Retired,Medium
1,1,51,100.6,1.68,11.99000,True,BLR,unemployed,High
2,2,67,114.8,1.74,0.61000,True,Mumbai,Retired,High
3,3,60,117.8,1.66,50.00000,True,Lucknow,business,High
4,4,40,70.0,1.59,28.16664,True,BLR,Govt_job,Low

In [ ]:
f.sample(5)

,Unnamed: 0,Age,Weight,Height,income_lpa,smoker,city,Occupation,INSURANCE_PREMIUM_category
3,3,60,117.8,1.66,50.00000,True,Lucknow,business,High
4,4,40,70.0,1.59,28.16664,True,BLR,Govt_job,Low
1,1,51,100.6,1.68,11.99000,True,BLR,unemployed,High
0,0,64,59.8,1.63,3.87000,False,Mumbai,Retired,Medium
2,2,67,114.8,1.74,0.61000,True,Mumbai,Retired,High

In [ ]:
f['Occupation'].unique()

array(['Retired', 'unemployed', 'business', 'Govt_job'], dtype=object)

In [ ]:
#creating a copy of our dataset because we will apply many feature engineering steps on our dataset
f_copy =  f.copy()
f_copy

,Unnamed: 0,Age,Weight,Height,income_lpa,smoker,city,Occupation,INSURANCE_PREMIUM_category
0,0,64,59.8,1.63,3.87000,False,Mumbai,Retired,Medium
1,1,51,100.6,1.68,11.99000,True,BLR,unemployed,High
2,2,67,114.8,1.74,0.61000,True,Mumbai,Retired,High
3,3,60,117.8,1.66,50.00000,True,Lucknow,business,High
4,4,40,70.0,1.59,28.16664,True,BLR,Govt_job,Low

In [ ]:
# Feature 1: maqking a new column (bmi)
f_copy["bmi"] = f_copy["Weight"] / (f_copy["Height"] ** 2)
f_copy

,Unnamed: 0,Age,Weight,Height,income_lpa,smoker,city,Occupation,INSURANCE_PREMIUM_category,bmi
0,0,64,59.8,1.63,3.87000,False,Mumbai,Retired,Medium,22.507433
1,1,51,100.6,1.68,11.99000,True,BLR,unemployed,High,35.643424
2,2,67,114.8,1.74,0.61000,True,Mumbai,Retired,High,37.917823
3,3,60,117.8,1.66,50.00000,True,Lucknow,business,High,42.749310
4,4,40,70.0,1.59,28.16664,True,BLR,Govt_job,Low,27.688778

In [ ]:
# Feature 2: Age_group
def age_group(Age):
  if Age < 25:
    return "young"
  elif Age < 45:
    return "adult"
  if Age < 60:
    return "middle_aged"
  return "senior"

In [ ]:
f_copy["Age_group"] = f_copy["Age"].apply(age_group)
f_copy

,Unnamed: 0,Age,Weight,Height,income_lpa,smoker,city,Occupation,INSURANCE_PREMIUM_category,bmi,Age_group
0,0,64,59.8,1.63,3.87000,False,Mumbai,Retired,Medium,22.507433,senior
1,1,51,100.6,1.68,11.99000,True,BLR,unemployed,High,35.643424,middle_aged
2,2,67,114.8,1.74,0.61000,True,Mumbai,Retired,High,37.917823,senior
3,3,60,117.8,1.66,50.00000,True,Lucknow,business,High,42.749310,senior
4,4,40,70.0,1.59,28.16664,True,BLR,Govt_job,Low,27.688778,adult

In [ ]:
#Feature 3: Lifestyle Risk
def lifestyle_risk(row):
  if row["smoker"] and row["bmi"] > 30:
    return "high"
  elif row["smoker"] and row["bmi"] > 27:
    return "medium"
  else:
    return "low"

In [ ]:
f_copy["Lifestyle_Risk"] = f_copy.apply(lifestyle_risk, axis=1)
f_copy

,Unnamed: 0,Age,Weight,Height,income_lpa,smoker,city,Occupation,INSURANCE_PREMIUM_category,bmi,Age_group,Lifestyle_Risk
0,0,64,59.8,1.63,3.87000,False,Mumbai,Retired,Medium,22.507433,senior,low
1,1,51,100.6,1.68,11.99000,True,BLR,unemployed,High,35.643424,middle_aged,high
2,2,67,114.8,1.74,0.61000,True,Mumbai,Retired,High,37.917823,senior,high
3,3,60,117.8,1.66,50.00000,True,Lucknow,business,High,42.749310,senior,high
4,4,40,70.0,1.59,28.16664,True,BLR,Govt_job,Low,27.688778,adult,medium

In [ ]:
#cities ko alag se process naa karke cities ko tiers me divide kar denge
tier_1_cities = {"Mumbai", "BLR", "Pondicherry", "Pune", "Chennai", "Kolkata"}

tier_2_cities = {"Jaipur", "Chandigarh", "Indore", "Patna", "Lucknow", "Coimbatore", "Ranchi", "Amristar", "Varanasi", "Guwahati", "Allahabad", "Aligarh", "Gaya"}

In [ ]:
#Feature 4:-> City tier
def city_tier(city):
    if city in tier_1_cities:
      return 1
    elif city in tier_2_cities:
      return 2
    else:
      return 3

In [ ]:
f_copy["City_tier"] =  f_copy["city"].apply(city_tier)
f_copy

,Unnamed: 0,Age,Weight,Height,income_lpa,smoker,city,Occupation,INSURANCE_PREMIUM_category,bmi,Age_group,Lifestyle_Risk,City_tier
0,0,64,59.8,1.63,3.87000,False,Mumbai,Retired,Medium,22.507433,senior,low,1
1,1,51,100.6,1.68,11.99000,True,BLR,unemployed,High,35.643424,middle_aged,high,1
2,2,67,114.8,1.74,0.61000,True,Mumbai,Retired,High,37.917823,senior,high,1
3,3,60,117.8,1.66,50.00000,True,Lucknow,business,High,42.749310,senior,high,2
4,4,40,70.0,1.59,28.16664,True,BLR,Govt_job,Low,27.688778,adult,medium,1

In [ ]:
# ab upar yeh saare humaare naye features aa gaye hai, yeh sab new features banne ke baad, hum kuch puraane features ko delete kar denge like AGE kyuki uske badle age_group aa gayaa
#height and wei8 ki zaroorat nhi hai kyuki uske badle bmi aa gayaa
#smoker ki zaroorat nhi hai kyuki uske badle lifestyle_risk aa gayaa
#city ki zaroorat nhi hai kyuki uske badle city_tier aa gayaa

f_copy.drop(columns=["Age", "Weight", "Height", "smoker", "city"])[["income_lpa", "Occupation", "bmi", "Age_group", "Lifestyle_Risk", "City_tier", "income_lpa", "INSURANCE_PREMIUM_category"]]

,income_lpa,Occupation,bmi,Age_group,Lifestyle_Risk,City_tier,income_lpa,INSURANCE_PREMIUM_category
0,3.87000,Retired,22.507433,senior,low,1,3.87000,Medium
1,11.99000,unemployed,35.643424,middle_aged,high,1,11.99000,High
2,0.61000,Retired,37.917823,senior,high,1,0.61000,High
3,50.00000,business,42.749310,senior,high,2,50.00000,High
4,28.16664,Govt_job,27.688778,adult,medium,1,28.16664,Low

***now we will train our Model using the above DATASET***

In [ ]:
#sabse pehle humne humara X and Y ko alg alag kar liiyaa, where Y is the TARGET column and X is our features
x = f_copy[["bmi", "Age_group", "Lifestyle_Risk", "City_tier", "income_lpa", "Occupation"]]
y = f_copy["INSURANCE_PREMIUM_category"]

In [ ]:
x

         bmi    Age_group Lifestyle_Risk  City_tier  income_lpa  Occupation
0  22.507433       senior            low          1     3.87000     Retired
1  35.643424  middle_aged           high          1    11.99000  unemployed
2  37.917823       senior           high          1     0.61000     Retired
3  42.749310       senior           high          2    50.00000    business
4  27.688778        adult         medium          1    28.16664    Govt_job

In [ ]:
y

0    Medium
1      High
2      High
3      High
4       Low
Name: INSURANCE_PREMIUM_category, dtype: object

In [ ]:
# Defined our CATEGORICAL and NUMERICAL features alag se, aise isiliye kiya yuki aaget on categorical features we will apply 1-hot encoding
categorical_features = ["Age_group", "Lifestyle_Risk", "City_tier", "Occupation"]
numerical_features = ["bmi", "income_lpa"]

In [ ]:
#created a column transformer and is columntransformer me saare categorical features ke upar 1-hot encoding lagaa diya aur
#saare numerical features ko as it is passthrough karaa diya, uske upar koi transformation nhi kiya
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(), categorical_features),
        ("num", "passthrough", numerical_features)
    ]
)

In [ ]:
#phir humne ek sk learn pipeline banai in 2 steps
#pehla, column transformer wala(preprocessor)
#2nd, hum us transformed data ke upar ek randomForestClassifier ko train kar rahe hai
pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", RandomForestClassifier(random_state=42))

])

In [ ]:

#LAST STEP : humne train_test_split karke apne x y ko training and test data me cut kiya(x_test, y_test) aur phir pipeline.fit ko call karke, model ko train kr liya
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
pipeline.fit(x_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  ['Age_group',
                                                   'Lifestyle_Risk',
                                                   'City_tier', 'Occupation']),
                                                 ('num', 'passthrough',
                                                  ['bmi', 'income_lpa'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [ ]:
#predict the value
y_pred = pipeline.predict(x_test)
accuracy_score(y_test, y_pred)

1.0

In [ ]:
#thus yeh jo model upar banaa hai, isko hume DOWNLOAD kar lena hai using pickle
import pickle

pickle_model_path = "modelOur.pkl"
with open(pickle_model_path, "wb") as f:
    pickle.dump(pipeline, f)

***MODEL BUILDING is complete which was our STEP 1***

***Now, we will create an END POINT for this model of ours using FAST API***

In [ ]:
#here in building API the HTTP method we will use is POST,
#kyu POST? :-> POST is used when a client wants to send some data to a server or client chahta hai ki SERVER is DATA ko process kare and process karke bohot chize ki ja sakta hai
#like ek nayaa resource create ki ja sakti hai, ya phir ek ML Model ka inference karaaya ja sakta hai etc etc
#hum client ki side se REQ BODY me kuch i/p bhejenge..kya i/p bhjna hai? hum kisi ek given user ka sara ka sara i/p features bhejenge like age, wei8, height(ORIGINAL DATA)
#all these features will be validated,once validated then using these features we will calculate the additional features like(bmi, age_grp, lifestyle_risk, cuty tier etcetc)
#and phir yeh saare features ko ML MODEL me bhejenge and model predict karke JSON ke form me o/p dega(HIGH, MEDIUM, LOW) which will be displayed in our front-end

*Now Open ur INTELLIJ IDEA to make the API*

In [ ]:
print(sklearn.__version__)

1.6.1

In [ ]:
from fastapi import FastAPI
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field, computed_field
from typing import Literal, Annotated
import pickle
import pandas as pd

#we have pasted model.pkl file here which we downloaded from colab

# IMPORTING the ML Model, Using FILE-HANDLING
with open('model.pkl', 'rb') as f: #we wanna open it in read binary mode b/c it's a binary file(rb)
    model = pickle.load(f)

#now we will make an obj of FastAPI
app = FastAPI()

#we will now make a pydantic model to validate incoming data(ORIGINAL DATA)
class UserInput(BaseModel):
    Age: Annotated[int, Field(..., gt=0, lt=120, description='Age of the user')]
    Weight: Annotated[float, Field(..., gt=0, lt=180, description='Weight of the user')]
    Height: Annotated[float, Field(..., gt=0, lt=2.5, description='Height of the user')]
    income_lpa: Annotated[float, Field(..., gt=0, description='Annual Salary of the user in L.P.A')]
    smoker: Annotated[bool, Field(..., description='is user a smoker?')]
    city: Annotated[str, Field(..., description='The City of the user')]
    Occupation: Annotated[Literal['Retired', 'unemployed', 'business', 'Govt_job'], Field(..., description='The City of the user')]  #this will be a Literal kyuki hum isme options denaa chahte hai

#Now hume in sab features se naye features banaane hai like hume (age_grp, bmi, etc etc lifestyle_risk) etc ye sab banaani hai
#Thus we will use computed_fields to compute these values
@computed_field    #for BMI
@property
def bmi(self) -> float:
    return self.weight/(self.height**2)

@computed_field   #FOR lIFESTYLE_RISK
@property
def lifestyle_risk(self) -> str:
    if self.smoker and self.bmi > 30:
        return "high"
    if self.smoker and self.bmi > 27:
        return "medium"
    else:
        return "low"

@computed_field    #for AGE_GROUP
@property
def age_group(self) -> str:
    if self.Age < 25:
        return "young"
    elif self.Age < 45:
        return "adult"
    elif self.Age < 60:
        return "middle_aged"
    return "senior"


tier_1_cities = {"Mumbai", "BLR", "Pondicherry", "Pune", "Chennai", "Kolkata"}
tier_2_cities = {"Jaipur", "Chandigarh", "Indore", "Patna", "Lucknow", "Coimbatore", "Ranchi", "Amristar", "Varanasi", "Guwahati", "Allahabad", "Aligarh", "Gaya"}
@computed_field    #for CITY_TIER
@property
def city_tier(self) -> int:
    if self.city in tier_1_cities:
        return 1
    elif self.city in tier_2_cities:
        return 2
    else:
        return 3

#PYDANTIC MODEL ban gayaaa, now we will make our END POINT(/predict)
@app.post('/predict')
def predict_premium(data: UserInput): #is func ko i/p me user ka data milega and yeh user ka data kaun se type ka hogaa? UserInput type ka hogaa, the class we made above, means REQ BODY se data ayega jo seedha chala jaayega humare pyd model(UserInput) ke paas, pyd model us data ke upar kaam karega , validate karega, computed fields nikaalega aur phir wo palat ke hume (data) ke form me yaha par mil jayega
    #ab hume bas proper i/p format create karna hai, thus ek ek karke row ka data pass karne hain hume humaare model me(TRANSFORMED_DATA JO hai like bmi, age grp etc etc)
    #and ye i/ps jo bheja jayega , ye pandas dataframe ke format me bheja jayega b/c Our RandomForestClassifier is trained upon a dataframe object
    input_df = pd.DataFrame([{   #naya d.f bana raha hu and is dataframe me sirf ek row rakhne wale hai jiske andar we will pass a dict jisme bmi ki value hogi, age_group ki value bhi rahegi and other transformed_features
        'bmi' : data.bmi,
        'Age_group' : data.age_group,
        'Lifestyle_risk' : data.lifestyle_risk,
        'City_tier' : data.city_tier,
        'income_lpa' : data.income_lpa,
        'Occupation' : data.Occupation
    }]) #and finally we stored this d.f in a variable input_df
      #thus yeh ban gayaa humara i/p, jo hum apne ML MOdel ke paas bhejenge

    #upar jo MODEL ko humne import kiya hai, uska PREDICT Func ko hum call karenge and iske andar hum pass kar denge apnaa input_df
    prediction = model.predict(input_df)[0] #issey hume ek list me o/p milega aur us list ka 0th item hume chaiye hogaa and this will be our prediction
     #isi prediction ko hume JSON Format me return karna hai

    return JSONResponse(status_code=200, content={'predicted_category': prediction})

In [ ]:
!uvicorn MLModelsviaFastApi:app --reload

INFO:     Will watch for changes in these directories: ['/content']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [8789] using WatchFiles
ERROR:    Error loading ASGI app. Could not import module "MLModelsviaFastApi".